// <auto-generated/>
#nullable enable

namespace JsonSerializerSample
{
    internal partial class BooksJsonContext
    {
        
        private static readonly global::System.Text.Json.JsonEncodedText PropName_title = global::System.Text.Json.JsonEncodedText.Encode("title");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_publisher = global::System.Text.Json.JsonEncodedText.Encode("publisher");
    }
}
