// <auto-generated/>
#nullable enable

namespace JsonSerializerSample
{
    internal partial class BooksJsonContext
    {
        
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Title = global::System.Text.Json.JsonEncodedText.Encode("Title");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Publisher = global::System.Text.Json.JsonEncodedText.Encode("Publisher");
    }
}
