// <auto-generated/>
#nullable enable

namespace JsonSerializerSample
{
    internal partial class BooksJsonContext
    {
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo GetTypeInfo(global::System.Type type)
        {
            if (type == typeof(global::JsonSerializerSample.Book))
            {
                return this.Book;
            }
        
            if (type == typeof(global::System.String))
            {
                return this.String;
            }
        
            return null!;
        }
    }
}
